website/models.py
from . import db
# from flask_login import UserMixin


class History(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bot = db.Column(db.String(500))
    user = db.Column(db.String(50))

website/__init__.py
from flask import Flask, Blueprint
from flask_sqlalchemy import SQLAlchemy

DB_NAME = "database.db"
db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "abc123"
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
    db.init_app(app)
    from .views import views
    app.register_blueprint(views, url_prefix='/')
    from .models import History
    with app.app_context():
        db.create_all()
        print("Database created!")
    return app

website/views.py
from flask import Blueprint, render_template, request, url_for, redirect
from langchain.vectorstores import Chroma
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from transformers import pipeline
import torch
from langchain.llms import HuggingFacePipeline
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.chains import RetrievalQA
import pandas as pd
from .models import History
from . import db

views = Blueprint('views', __name__)


def chat(chat_history, user_input):
    bot_response = qa_chain({"query": user_input})
    bot_response = bot_response['result']
    response = "".join(bot_response)
    chat_history.append((user_input, response))
    return chat_history


dataset_path = 'Sample-Advocates_Database.csv'
advocate_data = pd.read_csv(dataset_path, encoding='unicode_escape')
checkpoint = "MBZUAI/LaMini-Flan-T5-783M"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

# # Load the model with offload_folder argument
# base_model = AutoModelForSeq2SeqLM.from_pretrained(
#     checkpoint,
#     offload_folder="ipc_vector_data/92ca7e32-064c-43f8-973e-1060c76a995e",  # Replace with the actual path
#     device_map="auto",
#     torch_dtype=torch.float32
# )
#
# embeddings = SentenceTransformerEmbeddings(model_name="sentence-transformers/multi-qa-mpnet-base-dot-v1")
#
# db = Chroma(persist_directory="ipc_vector_data", embedding_function=embeddings)
#
# pipe = pipeline(
#     'text2text-generation',
#     model=base_model,
#     tokenizer=tokenizer,
#     max_length=10000,
#     do_sample=True,
#     temperature=1,
#     top_p=0.95
# )
# local_llm = HuggingFacePipeline(pipeline=pipe)
#
# qa_chain = RetrievalQA.from_chain_type(
#     llm=local_llm,
#     chain_type='stuff',
#     retriever=db.as_retriever(search_type="similarity", search_kwargs={"k": 2}),
#     return_source_documents=True,
# )

# Example usage
# chat_history = []
# user_input = input("Enter your initial input: ")
# chat_history = chat(chat_history, user_input)

# Display the conversation history
# for prompt, response in chat_history:
#     print(f"User: {prompt}")
#     print(f"Saul: {response}")


@views.route('/')
def home():
    return render_template("home.html")


@views.route('input', methods=['POST', 'GET'])
def Input():
    if request.method == 'POST':
        global qa_chain
        chat_history = []
        # Load the model with offload_folder argument
        base_model = AutoModelForSeq2SeqLM.from_pretrained(
            checkpoint,
            offload_folder="ipc_vector_data/92ca7e32-064c-43f8-973e-1060c76a995e",  # Replace with the actual path
            device_map="auto",
            torch_dtype=torch.float32
        )

        embeddings = SentenceTransformerEmbeddings(model_name="sentence-transformers/multi-qa-mpnet-base-dot-v1")

        dbb = Chroma(persist_directory="ipc_vector_data", embedding_function=embeddings)

        pipe = pipeline(
            'text2text-generation',
            model=base_model,
            tokenizer=tokenizer,
            max_length=10000,
            do_sample=True,
            temperature=1,
            top_p=0.95
        )
        local_llm = HuggingFacePipeline(pipeline=pipe)

        qa_chain = RetrievalQA.from_chain_type(
            llm=local_llm,
            chain_type='stuff',
            retriever=dbb.as_retriever(search_type="similarity", search_kwargs={"k": 2}),
            return_source_documents=True,
        )
        inp = request.form.get('input')
        chat_history = chat(chat_history, inp)
        # for prompt, response in chat_history:
        #     print(f"User: {prompt}")
        #     print(f"Saul: {response}")
        # return "<h1>Finished</h1>"
        if chat_history:
            for prompt, response in chat_history:
                hist = History(user=prompt, bot=response)
                db.session.add(hist)
                db.session.commit()
        return render_template("output.html", chat_history=chat_history)
    return render_template("input.html")


@views.route('search', methods=['POST'])
def search():
    search_term = request.form.get('address')

    # Filter the dataset based on the entered address
    filtered_data = advocate_data[advocate_data['ADDRESS'].str.contains(search_term, case=False, na=False)]
    columns_to_keep_indices = [0, 1, 4]

    # Create a new DataFrame with only the specified columns
    df_filtered = advocate_data.iloc[:, columns_to_keep_indices]

    # Save the new DataFrame to a new CSV file
    df_filtered.to_csv('new_file.csv', index=False)
    return render_template('search_result.html', data=filtered_data)


@views.route('history')
def history():
    items = History.query.all()
    return render_template("history.html", items=items)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
</head>
<body>
{% block location %}
    <div class="cta-search-bar">
        <form action="/search" method="post">

            <input type="text" id="address" name="address" placeholder="Want Lawyers? Enter your location!" required>
            <button type="submit"><img src="{{ url_for('static', filename='img/search.svg') }}" alt=""></button>
        </form>
    </div>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

website/templates/history.html
{% extends 'base.html' %}
{% block title %}History{% endblock %}
{% block location %}
{% endblock %}
{% block content %}
<h1>History</h1>
<section class="cta-table-main">
    <div class="container">
        <table class="rwd-table">
            <tbody>
                <tr>

                        <th>Requested prompt</th>
                        <th>Response</th>

                </tr>
                {% if items %}
                {% for item in items %}
                    <tr>
                            <td>{{ item.user }}</td>
                            <td>{{ item.bot }}</td>
                    </tr>
                {% endfor %}
                {% else %}
                <tr>
                            <td>None</td>
                            <td>None</td>
                    </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block location %}{% endblock %}
{% block content %}

 <section class="home">
    <img src="{{ url_for('static', filename='img/homebg.png') }}" alt="">
<p>Hello! I'm Saul, Saul Goodman your personal legal advisor. you have any doubt about your Civil rights ? Well! I am here to help you ask Any question Regarding it And i will provide you the best legal solution than any other lawyers out there. Civil rights ? 'Better Call Saul' </p>
<a href="{{ url_for('views.Input') }}">Start</a>
    </section>
{% endblock %}

website/templates/input.html
{% extends 'base.html' %}
{% block title %}Input Page{% endblock %}
{% block content %}
<div class="cta-two-button">
<a class="cta-back-to-home" href="{{ url_for('views.home') }}">Back to home</a>
<a class="cta-back-to-home" href="{{ url_for('views.history') }}"><h4>See History</h4></a>
    </div>
    <section class="chatbot-main">

   <div class="cta-input">
            <form method="post">
                <label>Say your query</label>
                 <div class="cta-input-section">
                <textarea type="text" name="input" id="input" required cols="50" rows="20" ></textarea>
                <button type="submit">Send</button>
             </div>
            </form>
        </div>

         <div class="cta-output">
            <div class="cta-user-prompt">
                <img src="{{ url_for('static', filename='img/user.svg') }}" alt="">
                <p>User prompt </p>
            </div>
            <div class="cta-bot-prompt">

                <p>Bot prompt </p>
                <img src="{{ url_for('static', filename='img/bot.svg') }}" alt="">
            </div>
        </div>
          </section>
{% endblock %}

website/templates/output.html
{% extends 'base.html' %}
{% block title %}Output Page{% endblock %}
{% block content %}
{% for prompt, response in chat_history %}
<div class="cta-two-button">
<a class="cta-back-to-home" href="{{ url_for('views.home') }}">Back to home</a>
<a class="cta-back-to-home" href="{{ url_for('views.history') }}"><h4>See History</h4></a>
    </div>
    <section class="chatbot-main">

        <div class="cta-input">
            <form action="">
                <label >Say your query</label>
                <div class="cta-input-section">
                    <textarea type="text" name="input" id="input" required cols="50" rows="20" ></textarea>
                    <button type="submit">Send</button>
                </div>
            </form>
        </div>

        <div class="cta-output">
            <div class="cta-user-prompt">
                <img src="{{ url_for('static', filename='img/user.svg') }}" alt="">
                <p>{{ prompt }} </p>
            </div>
            <div class="cta-bot-prompt">

                <p>{{ response }} </p>
                <img src="{{ url_for('static', filename='img/bot.svg') }}" alt="">
            </div>
        </div>

    </section>
{% endfor %}
{% endblock %}

website/templates/search_result.html
{% extends 'base.html' %}
{% block title %}Search Result{% endblock %}
{% block content %}
<a class="cta-back-to-query" href="{{ url_for('views.Input') }}">Back to query</a>
<section class="cta-table-main">
    <div class="container">
        <table class="rwd-table">
            <tbody>
                <tr>
                    {% for col in data.columns %}
                        <th>{{ col }}</th>
                    {% endfor %}
                </tr>
                {% for _, row in data.iterrows() %}
                    <tr>
                        {% for _, value in row.items() %}
                            <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
<br>
<a class="cta-back-to-home" href="/">Back to home</a>
{% endblock %}